ccptags = {
    "pollution_1": "__proto__[polluted]=true",
    "pollution_2": "constructor.prototype.polluted=true",
    "pollution_3": "prototype.polluted=true",
    "pollution_4": "constructor.prototype.polluted=true",
    "pollution_5": "constructor['prototype']['polluted']=true",
    "pollution_6": "__proto__.polluted=true",
    "pollution_7": "__proto__[\'polluted\']=true",
    "pollution_8": "constructor['prototype']['polluted']=true",
    "pollution_9": "constructor.prototype.toString=()=>'polluted'",
    "pollution_10": "__defineGetter__('polluted',() => true)",
    "pollution_11": "constructor.prototype.__defineGetter__('polluted',() => true)",
    "pollution_12": "Object.prototype.polluted=true",
    "pollution_13": "Object.defineProperty({},'__proto__',{value:{polluted:true}})",
    "pollution_14": "constructor.prototype.polluted=false",
    "pollution_15": "Object.setPrototypeOf({},{polluted:true})",
    "pollution_16": "Object.assign(Object.prototype,{polluted:true})",
    "pollution_17": "Object.create(Object.prototype,{polluted:{value:true}})",
    "pollution_18": "Object.defineProperty(Object.prototype,'polluted',{value:true})",
    "pollution_19": "constructor.prototype.valueOf=()=>'polluted'",
    "pollution_20": "__proto__.polluted=false",
    "pollution_21": "constructor.prototype.hasOwnProperty=function(){return 'polluted'}",
    "pollution_22": "constructor.prototype.valueOf=function(){return 'polluted'}",
    "pollution_23": "Object.prototype.valueOf=function(){return 'polluted'}",
    "pollution_24": "__defineSetter__('polluted',() => {})",
    "pollution_25": "Object.prototype.__defineGetter__('polluted',() => true)",
    "pollution_26": "constructor.prototype.toString=function(){return 'polluted'}",
    "pollution_27": "constructor.prototype.isPrototypeOf=() => true",
    "pollution_28": "__proto__.hasOwnProperty='polluted'",
    "pollution_29": "constructor.prototype.isPrototypeOf=()=>'polluted'",
    "pollution_30": "__lookupGetter__('polluted')",
    "pollution_31": "Object.prototype.__proto__.polluted=true",
    "pollution_32": "__lookupSetter__('polluted')",
    "pollution_33": "__defineGetter__('polluted', () => 'polluted')",
    "pollution_34": "__defineSetter__('polluted',()=>'polluted')",
    "pollution_35": "constructor.prototype.__defineSetter__('polluted',() => true)",
    "pollution_36": "constructor.prototype.__proto__.polluted=true",
    "pollution_37": "Object.create({}, {polluted: {get() { return true; }}})",
    "pollution_38": "Object.prototype.constructor.prototype.polluted=true",
    "pollution_39": "constructor.prototype.__defineGetter__('polluted',() => {})",
    "pollution_40": "constructor.prototype.__defineSetter__('polluted',() => {})",
    "pollution_41": "Object.create(null).__proto__.polluted=true",
    "pollution_42": "Object.getPrototypeOf({}).polluted=true",
    "pollution_43": "Object.create(null)['__proto__']['polluted']=true",
    "pollution_44": "Object.prototype['__proto__'].polluted=true",
    "pollution_45": "Object.defineProperty(Object.prototype, 'polluted', {value:true})",
    "pollution_46": "__proto__.polluted='true'",
    "pollution_47": "Object.assign(__proto__, {polluted:true})",
    "pollution_48": "Object.defineProperty(Object.prototype,'polluted',{value:true})",
    "pollution_49": "constructor.prototype.__proto__.polluted='true'",
    "pollution_50": "Object.prototype.__proto__.polluted='polluted'",
    "pollution_51": "Object.prototype.constructor['polluted']=true",
    "pollution_52": "constructor['__proto__'].polluted=true",
    "pollution_53": "Object.defineProperty(Object.prototype, 'polluted', {value:true})",
    "pollution_54": "constructor.prototype.__lookupGetter__('polluted')",
    "pollution_55": "__defineSetter__('polluted', function(){})",
    "pollution_56": "Object.assign(Object.prototype,{polluted:'polluted'})",
    "pollution_57": "Object.setPrototypeOf({}, {polluted: 'polluted'})",
    "pollution_58": "Object.getPrototypeOf({}).polluted='true'",
    "pollution_59": "Object.defineProperty({}, '__proto__', {value:{polluted:true}})",
    "pollution_60": "Object.create(null)['__proto__'].polluted='true'",
    "pollution_61": "Object.create(null).__proto__.polluted='true'",
    "pollution_62": "Object.setPrototypeOf({},{polluted:'true'})",
    "pollution_63": "Object.prototype.__defineGetter__('polluted',() => true)",
    "pollution_64": "Object.create(null).polluted=true",
    "pollution_65": "Object.prototype.__defineGetter__('polluted',()=>'true')",
    "pollution_66": "__proto__[Symbol.iterator]=()=>true",
    "pollution_67": "Object.prototype.__proto__[Symbol.iterator]=()=>true",
    "pollution_68": "Object.prototype.__proto__[Symbol.toPrimitive]=()=>true",
    "pollution_69": "Object.prototype.__proto__[Symbol.hasInstance]=()=>true",
    "pollution_70": "Object.prototype.__defineSetter__('polluted',()=>true)",
    "pollution_71": "__proto__.polluted=(()=>{})()",
    "pollution_72": "constructor.prototype.__proto__.polluted=()=>true",
    "pollution_73": "constructor.prototype.__defineGetter__('polluted',()=>{})",
    "pollution_74": "constructor.prototype.__defineSetter__('polluted',()=>{})",
    "pollution_75": "Object.prototype.__defineSetter__('polluted',()=>{})",
    "pollution_76": "__proto__.polluted='injected'",
    "pollution_77": "Object.assign({}, {polluted:true})",
    "pollution_78": "constructor.prototype[\'polluted\']=()=>true",
    "pollution_79": "constructor.prototype[Symbol.toStringTag]='polluted'",
    "pollution_80": "Object.prototype.constructor.prototype[Symbol.toStringTag]='polluted'",
    "pollution_81": "constructor.prototype[\'__proto__\'][\'polluted\']=()=>true",
    "pollution_82": "constructor.prototype.polluted='polluted_value'",
    "pollution_83": "Object.prototype.constructor['polluted']='polluted_value'",
    "pollution_84": "Object.setPrototypeOf({}, {polluted:true})",
    "pollution_85": "__proto__.polluted='exploit'",
    "pollution_86": "constructor.prototype[\'polluted\']=()=>false",
    "pollution_87": "Object.prototype.__defineGetter__('polluted', () => {})",
    "pollution_88": "Object.setPrototypeOf({}, {polluted:false})",
    "pollution_89": "Object.defineProperty({}, '__proto__', {value:{polluted:false}})",
    "pollution_90": "Object.create({}, {polluted:{value:false}})",
    "pollution_91": "Object.assign({}, {polluted:false})",
    "pollution_92": "constructor.prototype.polluted=false",
    "pollution_93": "Object.setPrototypeOf({}, {polluted:'polluted'})",
    "pollution_94": "constructor.prototype.__proto__.polluted='test'",
    "pollution_95": "Object.create(Object.prototype, {polluted:{value:false}})",
    "pollution_96": "constructor.prototype.polluted='test_injection'",
    "pollution_97": "__proto__.polluted='new_value'",
    "pollution_98": "__proto__.polluted='overwrite_test'",
    "pollution_99": "constructor.prototype['polluted']='polluted_injection'",
    "pollution_100": "constructor.prototype[Symbol.toPrimitive]='polluted'",
    "pollution_101": "Object.prototype.constructor.prototype[Symbol.toPrimitive]='polluted'",
    "pollution_102": "constructor.prototype.polluted=true",
    "pollution_103": "Object.prototype.__proto__['polluted']='exploit_test'",
    "pollution_104": "Object.assign({}, {polluted:'exploit_test'})",
    "pollution_105": "constructor.prototype.polluted='overwritten_value'",
    "pollution_106": "__proto__.polluted='overwritten_injection'",
    "pollution_107": "constructor.prototype.polluted='pollution_test'",
    "pollution_108": "constructor.prototype[Symbol.toStringTag]='polluted_test'",
    "pollution_109": "constructor.prototype.polluted=false",
    "pollution_110": "__proto__.polluted=false",
    "pollution_111": "__proto__.polluted='reset_value'",
    "pollution_112": "constructor.prototype.polluted='test_value'",
    "pollution_113": "constructor.prototype['polluted']='overwrite_value'",
    "pollution_114": "constructor.prototype.polluted='test'",
    "pollution_115": "constructor.prototype['__proto__']['polluted']=false",
    "pollution_116": "__proto__[Symbol.toPrimitive]='polluted_test'",
    "pollution_117": "Object.prototype['polluted']='overwrite_pollution'",
    "pollution_118": "__proto__.polluted=false",
    "pollution_119": "__proto__.polluted='new_value_test'",
    "pollution_120": "Object.prototype.__proto__[Symbol.iterator]='polluted_value'",
    "pollution_121": "__proto__.polluted='final_test'",
    "pollution_122": "Object.setPrototypeOf({}, {polluted:'final_pollution'})",
    "pollution_123": "constructor.prototype.polluted='overwrite_final'",
    "pollution_124": "Object.assign(Object.prototype, {polluted:'overwrite_final_value'})",
    "pollution_125": "__proto__.polluted='overwrite_exploit'",
    "pollution_126": "constructor.prototype[Symbol.iterator]='polluted_injection'",
    "pollution_127": "constructor.prototype.polluted=true",
    "pollution_128": "__proto__.polluted='last_exploit'",
    "pollution_129": "Object.prototype.__proto__['polluted']='last_pollution'",
    "pollution_130": "__proto__.polluted='overwrite_last_test'",
    "pollution_131": "Object.prototype['polluted']='final_overwrite'",
    "pollution_132": "constructor.prototype['polluted']='test_overwrite'",
    "pollution_133": "constructor.prototype.polluted='overwrite_pollution_value'",
    "pollution_134": "__proto__.polluted='overwrite_final_test'",
    "pollution_135": "Object.assign({}, {polluted:'overwrite_last'})",
    "pollution_136": "constructor.prototype[Symbol.toStringTag]='polluted_final'",
    "pollution_137": "Object.prototype.constructor['polluted']='overwrite_final_value'",
    "pollution_138": "constructor.prototype[Symbol.hasInstance]='polluted_test'",
    "pollution_139": "Object.setPrototypeOf({}, {polluted:'overwrite_exploit'})",
    "pollution_140": "__proto__.polluted='overwrite_exploit_test'",
    "pollution_141": "Object.assign(Object.prototype,{polluted:'final_injection'})",
    "pollution_142": "__proto__.polluted='overwrite_final_test'",
    "pollution_143": "constructor.prototype.polluted='final_test_overwrite'",
    "pollution_144": "Object.prototype.__proto__[Symbol.iterator]='overwrite_final'",
    "pollution_145": "Object.defineProperty({}, '__proto__', {value:{polluted:true}})",
    "pollution_146": "__proto__[Symbol.toPrimitive]='final_injection_test'",
    "pollution_147": "__proto__.polluted='exploit_test_final'",
    "pollution_148": "constructor.prototype[Symbol.toStringTag]='overwrite_final_test'",
    "pollution_149": "__proto__.polluted='exploit_injection'",
    "pollution_150": "Object.prototype.constructor['polluted']='final_pollution_test'"
}
