cstitags = {
    'a': ['href', 'onclick'],
    'abbr': [],
    'address': [],
    'area': ['href', 'onclick'],
    'article': [],
    'aside': [],
    'audio': ['src', 'controls'],
    'b': [],
    'base': ['href'],
    'bdi': [],
    'bdo': [],
    'blockquote': ['cite'],
    'body': [],
    'br': [],
    'button': ['onclick', 'type'],
    'canvas': [],
    'caption': [],
    'cite': [],
    'code': [],
    'col': [],
    'colgroup': [],
    'data': [],
    'datalist': [],
    'dd': [],
    'del': ['cite'],
    'details': ['open'],
    'dfn': [],
    'dialog': [],
    'div': [],
    'dl': [],
    'dt': [],
    'em': [],
    'embed': ['src', 'type'],
    'fieldset': [],
    'figcaption': [],
    'figure': [],
    'footer': [],
    'form': ['action', 'method', 'onsubmit'],
    'h1': [],
    'h2': [],
    'h3': [],
    'h4': [],
    'h5': [],
    'h6': [],
    'head': [],
    'header': [],
    'hgroup': [],
    'hr': [],
    'html': [],
    'i': [],
    'iframe': ['src', 'sandbox'],
    'img': ['src', 'alt', 'onclick'],
    'input': ['type', 'value', 'onclick'],
    'ins': ['cite'],
    'kbd': [],
    'label': ['for'],
    'legend': [],
    'li': [],
    'link': ['href', 'rel'],
    'main': [],
    'map': [],
    'mark': [],
    'meta': ['name', 'content'],
    'meter': [],
    'nav': [],
    'noscript': [],
    'object': ['data', 'type'],
    'ol': [],
    'optgroup': [],
    'option': ['value'],
    'output': [],
    'p': [],
    'param': ['name', 'value'],
    'picture': [],
    'pre': [],
    'progress': [],
    'q': ['cite'],
    'rp': [],
    'rt': [],
    'ruby': [],
    's': [],
    'samp': [],
    'script': ['src'],
    'section': [],
    'select': ['multiple', 'size'],
    'small': [],
    'source': ['src', 'type'],
    'span': [],
    'strong': [],
    'style': ['type', 'src'],
    'sub': [],
    'summary': [],
    'sup': [],
    'table': [],
    'tbody': [],
    'td': [],
    'template': [],
    'textarea': ['cols', 'rows', 'onclick'],
    'tfoot': [],
    'th': [],
    'thead': [],
    'time': ['datetime'],
    'title': [],
    'tr': [],
    'track': ['src', 'kind', 'srclang', 'label'],
    'u': [],
    'ul': [],
    'var': [],
    'video': ['src', 'controls'],
    'wbr': [],
    'svg': [],
    'canvas': [],
    'math': [],
    'script': ['type', 'src'],
    'link': ['href', 'rel'],
    'meta': ['name', 'content'],
    'style': ['type'],
    'form': ['action', 'method', 'enctype'],
    'input': ['type', 'name', 'value', 'onclick'],
    'textarea': ['name', 'placeholder', 'onclick'],
    'button': ['onclick', 'type', 'name'],
    'select': ['name', 'multiple', 'size'],
    'option': ['value', 'selected'],
}